name: Sync to Hugging Face Space
on:
  push:
    branches: [ main ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Unshallow clone
      - name: Setup Git LFS
        run: git lfs install
      - name: Pull LFS Objects
        run: git lfs pull
      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config lfs.allowincompletepush true
          git remote add space https://oauth2:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/mihiringole/job-recommender
          git push space main --force
