name: Sync to Hugging Face Space
on:
  push:
    branches: [ main ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://oauth2:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/mihiringole/job-recommender
          git push space main --force
